Alias
giantswarm/irsa-operator pull request #66
Opened 2022-10-21 12:20 UTC by whites11

## Checklist

- [ ] Update changelog in CHANGELOG.md.

2022-11-17 13:49 UTC, calvix approved these changes
looks sane,  LGTM if properly tested

2022-11-17 14:11 UTC, whites11 commented
> looks sane, LGTM if properly tested

full testing is impossible right now to me. I wasn't able to create a cluster.
I have no idea how the last step between the secret containing irsa data and the API server flags is supposed to work (it does not at the moment) and thus I did only basic testing (ensuring irsa operator does what it's meant to.

2022-11-17 14:44 UTC, njuettner requested changes

2022-11-17 14:44 UTC, njuettner commented on pkg/irsa/capa/capa.go
> +	awscluster := &v1alpha3.AWSCluster{}
This must be `v1beta1`.

2022-11-17 16:09 UTC, whites11 commented on pkg/irsa/capa/capa.go
> +	awscluster := &v1alpha3.AWSCluster{}
bumped dependency and using v1beta1 now

2022-11-17 16:14 UTC, njuettner approved these changes
lgtm 🤗

2022-11-23 15:16 UTC, paurosello commented
LGTM

2022-11-23 15:16 UTC, merged